# Generated by Django 4.2.6 on 2023-11-05 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0002_student_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='doc_img',
            field=models.ImageField(default='', upload_to='doctor_image'),
        ),
    ]
